import os
import sys
import json
from datetime import datetime

# Add the current plugins directory to the path so we can import chief_of_staff_db
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
import chief_of_staff_db

def fetch_and_mark_notifications() -> str:
    """
    Queries the SQLite database for any pending outbound notifications/cron triggers,
    marks them as 'sent', and returns them as a combined prompt for the agent to action.

    Returns:
        str: A formatted string of pending alerts to process, or a message indicating no pending items.
    """
    try:
        pending_list = chief_of_staff_db.get_pending_notifications()
        if not pending_list:
            return "No pending notifications."

        response_parts = ["### PENDING SCHEDULED ALERTS TO PROCESS ###\n"]
        for idx, item in enumerate(pending_list, 1):
            # Mark as sent immediately to avoid processing loops
            chief_of_staff_db.update_notification_status(item["id"], "sent")
            
            # Log to telemetry
            chief_of_staff_db.log_telemetry(
                event_type="notification_processed",
                details={
                    "notification_id": item["id"],
                    "prompt": item["prompt"],
                    "processed_at": datetime.now().isoformat()
                }
            )
            response_parts.append(f"{idx}. [ID: {item['id']}] {item['prompt']}")

        response_parts.append("\nAction required: Please process the above alerts, generate the requested briefings or reminders, and deliver them to the user in your response.")
        return "\n".join(response_parts)

    except Exception as e:
        return f"Error fetching notifications from SQLite: {str(e)}"

def add_notification_tool(prompt: str) -> str:
    """Queues a new notification/reminder in the SQLite database."""
    try:
        notification_id = chief_of_staff_db.add_notification(prompt)
        return json.dumps({
            "success": True,
            "notification_id": notification_id,
            "message": f"Successfully queued notification with ID: {notification_id}"
        })
    except Exception as e:
        return json.dumps({
            "success": False,
            "error": str(e)
        })

def get_recent_telemetry_tool(days: int = 14, limit: int = 100) -> str:
    """Retrieves recent system and user compliance telemetry logs."""
    try:
        logs = chief_of_staff_db.get_recent_telemetry(days=days, limit=limit)
        return json.dumps({
            "success": True,
            "logs": [dict(log) for log in logs]
        })
    except Exception as e:
        return json.dumps({
            "success": False,
            "error": str(e)
        })

# Hermes agent plugin definition
def setup_plugin(registry):
    registry.register_tool(
        name="fetch_pending_notifications",
        func=fetch_and_mark_notifications,
        description="Checks the local SQLite queue for pending automated briefings or reminders generated by system cron jobs, marks them as processed, and returns their text so the agent can execute and send them to the user.",
    )
    registry.register_tool(
        name="add_notification",
        func=add_notification_tool,
        description="Queues a notification or reminder prompt in the SQLite database.",
    )
    registry.register_tool(
        name="get_recent_telemetry",
        func=get_recent_telemetry_tool,
        description="Retrieves recent system and user compliance telemetry logs from the database.",
    )
